import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { useSession, signOut, signIn, getSession, GetSessionParams } from 'next-auth/react'
import styles from '../styles/Home.module.css'
import { Schedule, GetSResults } from "../types";

const Home: NextPage<{ tasks: Schedule[] }> = ({ tasks }) => {
  const { data: session, status } = useSession();
  console.log(session)
  if (status === 'authenticated') {
    return (
      //TÄHÄN DESIGN
      <div className={styles.container}>
        <Head>
          <title>Home page</title>
          <h1>Welcome to the home page, {session?.user?.name}!</h1>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.card}>
            <button onClick={() => signOut()}>Sign out</button>
            <p>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of type
              and scrambled it to make a type specimen book. It has survived not
              only five centuries, but also the leap into electronic typesetting,
              remaining essentially unchanged. It was popularised in the 1960s
              with the release of Letraset sheets containing Lorem Ipsum passages,
              and more recently with desktop publishing software like Aldus
              PageMaker including versions of Lorem Ipsum.
            </p>
          </div>
          <div className={styles.card}>
            <p>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of type
              and scrambled it to make a type specimen book. It has survived not
              only five centuries, but also the leap into electronic typesetting,
              remaining essentially unchanged. It was popularised in the 1960s
              with the release of Letraset sheets containing Lorem Ipsum passages,
              and more recently with desktop publishing software like Aldus
              PageMaker including versions of Lorem Ipsum.
            </p>
          </div>
          <div className={styles.card}>
            <h1 className={styles.header}>Today's tasks</h1>
            {tasks.map((task) => {
              return (
                <ul key={task.id}>
                  <li className={styles.task}>{task.task1}</li>
                  <li className={styles.task}>{task.task2}</li>
                  <li className={styles.task}>{task.task3}</li>
                </ul>
              );
            })}
          </div>
        </main>
      </div>

    )
  } else {
    return (
      //TÄHÄN MYÖS
      <div>
        <p>You are not signed in.</p>
        <button onClick={() => signIn()}>Sign in</button>
      </div>
    )
  }
}
// export const getStaticProps: GetStaticProps = async (context) => {
//     //haetaan dummy json dataa
//     const res = await fetch(
//         "https://raw.githubusercontent.com/vhjaho/calendar/main/calendar.json"
//     );
//     //resultit tallennetaan
//     const { results }: GetSResults = await res.json();

//     return {
//         //apin lähettämät propsit nimetään = tasks
//         props: {
//             tasks: results,
//         },
//     };
// };

export default Home

export const getServerSideProps = async (context: GetSessionParams | undefined) => {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/login'
      }
    }
  }
  return {
    props: { session }
  }
}
//import Head from "next/head";
//import styles from "../styles/Home.module.css";
//import type { GetStaticProps, NextPage } from "next";
//import { Schedule, GetSResults } from "../types";

//const Home: NextPage<{ tasks: Schedule[] }> = ({ tasks }) => {
//  return (
//    <div className={styles.container}>
//      <Head>
//        <title>Home page</title>
//        <h1 className={styles.header}>Welcome to the home page!</h1>
//        <meta name="description" content="Generated by create next app" />
//        <link rel="icon" href="/favicon.ico" />
//      </Head>
//      <main className={styles.main}>
//        <div className={styles.card}>
//          <p>
//            Lorem Ipsum is simply dummy text of the printing and typesetting
//            industry. Lorem Ipsum has been the industry's standard dummy text
//            ever since the 1500s, when an unknown printer took a galley of type
//            and scrambled it to make a type specimen book. It has survived not
//            only five centuries, but also the leap into electronic typesetting,
//            remaining essentially unchanged. It was popularised in the 1960s
//            with the release of Letraset sheets containing Lorem Ipsum passages,
//            and more recently with desktop publishing software like Aldus
//            PageMaker including versions of Lorem Ipsum.
//          </p>
//        </div>
//        <div className={styles.card}>
//          <p>
//            Lorem Ipsum is simply dummy text of the printing and typesetting
//            industry. Lorem Ipsum has been the industry's standard dummy text
//            ever since the 1500s, when an unknown printer took a galley of type
//            and scrambled it to make a type specimen book. It has survived not
//            only five centuries, but also the leap into electronic typesetting,
//            remaining essentially unchanged. It was popularised in the 1960s
//            with the release of Letraset sheets containing Lorem Ipsum passages,
//            and more recently with desktop publishing software like Aldus
//            PageMaker including versions of Lorem Ipsum.
//          </p>
//        </div>
//        <div className={styles.card}>
//          <h1 className={styles.header}>Today's tasks</h1>
//          {tasks.map((task) => {
//            return (
//              <ul key={task.id}>
//                <li className={styles.task}>{task.task1}</li>
//                <li className={styles.task}>{task.task2}</li>
//                <li className={styles.task}>{task.task3}</li>
//              </ul>
//            );
//          })}
//        </div>
//      </main>
//    </div>
//  );
//};

//export const getStaticProps: GetStaticProps = async (context) => {
//  //haetaan dummy json dataa
//  const res = await fetch(
//    "https://raw.githubusercontent.com/vhjaho/calendar/main/calendar.json"
//  );
//  //resultit tallennetaan
//  const { results }: GetSResults = await res.json();

//  return {
//    //apin lähettämät propsit nimetään = tasks
//    props: {
//      tasks: results,
//    },
//  };
//};

//export default Home;
