name: Deployement pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployement_pipeline:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      #- name: Check out repository code.
      - uses: actions/checkout@v3
      #- name: Install node.js
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm install
        run: npm install --legacy-peer-deps

      - name: Lint test
        run: npm run lint
        env:
          CI: true

      - name: build
        run: npm run build

      - name: deploy
        id: deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # Deploy to heroku action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "next-calendar-app"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://next-calendar-app.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

      - name: Deployment Succeeded
        uses: rjstone/discord-webhook-notify@v1
        if: ${{success() && steps.deploy.conclusion == 'success' }}
        with:
          severity: info
          text: A new version of Pokedex deployed to
          description: https://next-calendar-app.herokuapp.com/ by ${{ github.actor }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deployment Failed
        uses: rjstone/discord-webhook-notify@v1
        if: ${{failure() && steps.deploy.conclusion == 'failure' }}
        with:
          severity: error
          text: Build failed
          description: ${{ github.sha }} by ${{ github.actor }} broke the build :(
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: deployement_pipeline
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
